# Copyright (c) 2026, Frappe Technologies Pvt. Ltd. and Contributors
# License: MIT. See LICENSE
import json

import frappe
from frappe.utils.data import orjson_dumps
from frappe.utils.jinja_globals import bundled_asset
from frappe.utils.response import json_handler
from frappe.www.desk import get_context as get_desk_context

no_cache = 1


def get_context(context):
	get_desk_context(context)

	# The Vue shell appends bundles itself (interleaving its native installs
	# between them), so hand it resolved asset URLs instead of the
	# include_script/include_style jinja helpers desk.html uses.
	for key in ("app_include_js", "app_include_css"):
		context[key] = [bundled_asset(asset) for asset in context[key]]

	# newdesk.html is generated by the frontend build (frappe-ui's jinjaBootData
	# vite plugin): it renders `window["<key>"] = {{ boot[<key>] | tojson }}` for
	# every key of context.boot. Pack everything the shell's initFrappe needs into
	# that dict. The desk boot holds datetimes that jinja's plain `tojson` can't
	# encode, so round-trip it through frappe's JSON serializer first.
	context.boot = frappe._dict(
		frappe_boot=json.loads(orjson_dumps(context.boot, default=json_handler)),
		csrf_token=context.csrf_token,
		app_include_js=context.app_include_js,
		app_include_css=context.app_include_css,
		app_include_icons=context.app_include_icons,
		build_version=context.build_version,
		desk_theme=context.desk_theme,
		app_name=context.app_name,
		lang=context.lang,
		layout_direction=context.layout_direction,
		favicon=context.favicon,
		sounds=context.sounds,
	)

	return context
